const optionNames = {
  en: {
    accessories: {
      kurt: "Kurt",
      prescription01: "Prescription 1",
      prescription02: "Prescription 2",
      round: "Round",
      sunglasses: "Sunglasses",
      wayfarers: "Wayfarers",
      eyepatch: "Eyepatch",
      nothing: "None",
    },
    top: {
      hat: "Hat",
      hijab: "Hijab",
      turban: "Turban",
      winterHat1: "Winter Hat 1",
      winterHat02: "Winter Hat 2",
      winterHat03: "Winter Hat 3",
      winterHat04: "Winter Hat 4",
      bob: "Bob",
      bun: "Bun",
      curly: "Curly",
      curvy: "Wavy",
      dreads: "Dreads",
      frida: "Frida",
      fro: "Afro",
      froBand: "Afro Band",
      longButNotTooLong: "Medium Long",
      miaWallace: "Mia Wallace",
      shavedSides: "Shaved Sides",
      straight01: "Straight 1",
      straight02: "Straight 2",
      straightAndStrand: "Straight & Strand",
      dreads01: "Dreads 1",
      dreads02: "Dreads 2",
      frizzle: "Frizzle",
      shaggy: "Shaggy",
      shaggyMullet: "Shaggy Mullet",
      shortCurly: "Short Curly",
      shortFlat: "Short Flat",
      shortRound: "Short Round",
      shortWaved: "Short Wavy",
      sides: "Sides",
      theCaesar: "Caesar",
      theCaesarAndSidePart: "Caesar Side Part",
      bigHair: "Big Hair",
      bald: "Bald",
    },
    eyebrows: {
      angryNatural: "Angry Natural",
      defaultNatural: "Default Natural",
      flatNatural: "Flat Natural",
      frownNatural: "Frown Natural",
      raisedExcitedNatural: "Raised Natural",
      sadConcernedNatural: "Sad Natural",
      unibrowNatural: "Unibrow Natural",
      upDownNatural: "Up-Down Natural",
      angry: "Angry",
      default: "Default",
      raisedExcited: "Raised",
      sadConcerned: "Sad",
      upDown: "Up-Down",
    },
    eyes: {
      closed: "Closed",
      cry: "Crying",
      default: "Default",
      eyeRoll: "Eye Roll",
      happy: "Happy",
      hearts: "Hearts",
      side: "Side Look",
      squint: "Squint",
      surprised: "Surprised",
      winkWacky: "Wacky Wink",
      wink: "Wink",
      xDizzy: "Dizzy",
    },
    facialHair: {
      beardLight: "Light Beard",
      beardMajestic: "Majestic Beard",
      beardMedium: "Medium Beard",
      moustacheFancy: "Fancy Moustache",
      moustacheMagnum: "Magnum Moustache",
      nothing: "None",
    },
    mouth: {
      concerned: "Concerned",
      default: "Default",
      disbelief: "Disbelief",
      eating: "Eating",
      grimace: "Grimace",
      sad: "Sad",
      screamOpen: "Scream",
      serious: "Serious",
      smile: "Smile",
      tongue: "Tongue",
      twinkle: "Twinkle",
      vomit: "Vomit",
    },
    clothing: {
      blazerAndShirt: "Blazer & Shirt",
      blazerAndSweater: "Blazer & Sweater",
      collarAndSweater: "Collar & Sweater",
      graphicShirt: "Graphic Shirt",
      hoodie: "Hoodie",
      overall: "Overall",
      shirtCrewNeck: "Crew Neck",
      shirtScoopNeck: "Scoop Neck",
      shirtVNeck: "V-Neck",
    },
    clothingGraphic: {
      bat: "Bat",
      bear: "Bear",
      cumbia: "Cumbia",
      deer: "Deer",
      diamond: "Diamond",
      hola: "Hola",
      pizza: "Pizza",
      resist: "Resist",
      skull: "Skull",
      skullOutline: "Skull Outline",
      nothing: "None",
    },
  },
  fr: {
    accessories: {
      kurt: "Kurt",
      prescription01: "Lunettes de vue 1",
      prescription02: "Lunettes de vue 2",
      round: "Rondes",
      sunglasses: "Lunettes de soleil",
      wayfarers: "Wayfarers",
      eyepatch: "Cache-\u0153il",
      nothing: "Aucun",
    },
    top: {
      hat: "Chapeau",
      hijab: "Hijab",
      turban: "Turban",
      winterHat1: "Bonnet 1",
      winterHat02: "Bonnet 2",
      winterHat03: "Bonnet 3",
      winterHat04: "Bonnet 4",
      bob: "Carr\u00e9",
      bun: "Chignon",
      curly: "Boucl\u00e9",
      curvy: "Ondul\u00e9",
      dreads: "Dreads",
      frida: "Frida",
      fro: "Afro",
      froBand: "Afro avec bandeau",
      longButNotTooLong: "Mi-long",
      miaWallace: "Mia Wallace",
      shavedSides: "C\u00f4t\u00e9s ras\u00e9s",
      straight01: "Lisses 1",
      straight02: "Lisses 2",
      straightAndStrand: "Lisse avec m\u00e8che",
      dreads01: "Dreads 1",
      dreads02: "Dreads 2",
      frizzle: "Fris\u00e9",
      shaggy: "\u00c9bouriff\u00e9",
      shaggyMullet: "Mulet \u00e9bouriff\u00e9",
      shortCurly: "Court boucl\u00e9",
      shortFlat: "Court plat",
      shortRound: "Court rond",
      shortWaved: "Court ondul\u00e9",
      sides: "D\u00e9grad\u00e9",
      theCaesar: "C\u00e9sar",
      theCaesarAndSidePart: "C\u00e9sar avec raie",
      bigHair: "Grosse coiffure",
      bald: "Chauve",
    },
    eyebrows: {
      angryNatural: "Naturels en col\u00e8re",
      defaultNatural: "Naturels",
      flatNatural: "Naturels plats",
      frownNatural: "Naturels fronc\u00e9s",
      raisedExcitedNatural: "Naturels relev\u00e9s",
      sadConcernedNatural: "Naturels tristes",
      unibrowNatural: "Monosourcil naturel",
      upDownNatural: "Naturels asym\u00e9triques",
      angry: "En col\u00e8re",
      default: "Par d\u00e9faut",
      raisedExcited: "Relev\u00e9s",
      sadConcerned: "Tristes",
      upDown: "Asym\u00e9triques",
    },
    eyes: {
      closed: "Ferm\u00e9s",
      cry: "En pleurs",
      default: "Par d\u00e9faut",
      eyeRoll: "Yeux lev\u00e9s",
      happy: "Joyeux",
      hearts: "C\u0153urs",
      side: "De c\u00f4t\u00e9",
      squint: "Pliss\u00e9s",
      surprised: "Surpris",
      winkWacky: "Clin d'\u0153il fou",
      wink: "Clin d'\u0153il",
      xDizzy: "\u00c9tourdis",
    },
    facialHair: {
      beardLight: "Barbe l\u00e9g\u00e8re",
      beardMajestic: "Barbe majestueuse",
      beardMedium: "Barbe moyenne",
      moustacheFancy: "Moustache \u00e9l\u00e9gante",
      moustacheMagnum: "Moustache Magnum",
      nothing: "Aucune",
    },
    mouth: {
      concerned: "Inquiet",
      default: "Par d\u00e9faut",
      disbelief: "Incr\u00e9dule",
      eating: "En train de manger",
      grimace: "Grimace",
      sad: "Triste",
      screamOpen: "Cri",
      serious: "S\u00e9rieux",
      smile: "Sourire",
      tongue: "Langue tir\u00e9e",
      twinkle: "Malicieux",
      vomit: "Vomi",
    },
    clothing: {
      blazerAndShirt: "Blazer et chemise",
      blazerAndSweater: "Blazer et pull",
      collarAndSweater: "Col et pull",
      graphicShirt: "T-shirt imprim\u00e9",
      hoodie: "Sweat \u00e0 capuche",
      overall: "Salopette",
      shirtCrewNeck: "Col rond",
      shirtScoopNeck: "Col \u00e9chancr\u00e9",
      shirtVNeck: "Col en V",
    },
    clothingGraphic: {
      bat: "Chauve-souris",
      bear: "Ours",
      cumbia: "Cumbia",
      deer: "Cerf",
      diamond: "Diamant",
      hola: "Hola",
      pizza: "Pizza",
      resist: "Resist",
      skull: "Cr\u00e2ne",
      skullOutline: "Contour de cr\u00e2ne",
      nothing: "Aucun",
    },
  },
};

export function getOptionName(path, value, lang = "en") {
  const langKey = lang.substring(0, 2);
  const names = optionNames[langKey] || optionNames.en;
  const attrNames = names[path];
  if (!attrNames) return value;
  return attrNames[value] || value;
}
