// const initialPlayersList = [
//   {
//     id: 0,
//     name: "Player 0",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 1,
//     name: "Player 1",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 2,
//     name: "Player 2",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 3,
//     name: "Player 3",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 4,
//     name: "Player 4",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 5,
//     name: "Player 5",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 6,
//     name: "Player 6",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 7,
//     name: "Player 7",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 8,
//     name: "Player 8",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 9,
//     name: "Player 9",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 10,
//     name: "Player 10",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 11,
//     name: "Player 11",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 12,
//     name: "Player 12",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 13,
//     name: "Player 13",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 14,
//     name: "Player 14",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
//   {
//     id: 15,
//     name: "Player 15",
//     avatar: "",
//     role: "",
//     isAlive: true,
//     isRevealed: false,
//     voteAgainst: 0,
//     isUnderArrest: false,
//   },
// ];

// export default initialPlayersList;
