import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <main className="flex h-screen w-screen flex-col items-center p-16">
          {children}
        </main>
      </body>
    </html>
  );
}
